config/routes.rb
Rails.application.routes.draw do
  get 'book_statuses/index'
  root 'users#top'
  devise_for :users
  resources :users, only:[:show] do
    resources :favorite_authors, only:[:index]
    resources :book_statuses, only:[:index]
  end

  resources :books, only:[:show, :index] do
    resources :book_statuses, only:[:create, :update, :destroy]
    resources :reviews, only:[:create, :update, :destroy] do
      resource :good_reviews, only:[:create, :destroy]
    end
    resources :responses, only:[:create, :destroy]
    resource :favorite_book, only:[:create, :destroy]
  end

  resources :authors, only:[:show, :index] do
    resource :favorite_authors, only:[:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy

  has_many :favorite_authors, dependent: :destroy
  def favorite_author_by?(user)
    favorite_authors.where(user_id: user.id).exists?
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :book_statuses, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :responses, dependent: :destroy

  has_many :favorite_books, dependent: :destroy
  def favorite_book_by?(user)
    favorite_books.where(user_id: user.id).exists?
  end

end

app/models/book_status.rb
class BookStatus < ApplicationRecord
  belongs_to :user
  belongs_to :book

  enum status: { check: 0, read: 1, finish: 2 }

end

app/models/favorite_author.rb
class FavoriteAuthor < ApplicationRecord
  belongs_to :author
  belongs_to :user
end

app/models/favorite_book.rb
class FavoriteBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/good_review.rb
class GoodReview < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book

  has_many :good_reviews, dependent: :destroy
  def good_review_by?(user)
    good_reviews.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorite_authors, dependent: :destroy
  has_many :book_statuses, dependent: :destroy
  has_many :favorite_books, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_many :good_reviews, dependent: :destroy

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def show
    @author = Author.find(params[:id])
  end

  def index
    @authors = Author.all
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @book_status = current_user.book_statuses.find_by(book_id: @book.id)
    @review = current_user.reviews.find_by(book_id: @book)
    # 「自分以外全員」のレビューの取得
    @reviews = @book.reviews.where.not(user_id: current_user.id)
    @responses = @book.responses
    
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    review = current_user.reviews.new(review_params)
    review.book_id = book.id
    review.save
    redirect_back(fallback_location: root_path)
  end

  def update
    book = Book.find(params[:book_id])
    review = book.reviews.find(params[:id])
    review.update(review_params)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    review = book.reviews.find(params[:id])
    review.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def review_params
    params.require(:review).permit(:text)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def top
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_statuses_helper.rb
module BookStatusesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorite_books_helper.rb
module FavoriteBooksHelper
end

app/helpers/good_reviews_helper.rb
module GoodReviewsHelper
end

app/helpers/resposes_helper.rb
module ResposesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/index.html.erb
<h1>著者一覧</h1>

<% @authors.each do |author| %>
  <div>
    <%= link_to author.name, author_path(author.id) %>
  </div>
<% end %>

app/views/authors/show.html.erb
<h1><%= @author.name %>'sページ</h1>

<div>
  <% if @author.favorite_author_by?(current_user) %>
    お気に入り登録済みです
    <%= link_to "登録を外す", author_favorite_authors_path(@author.id), method: :delete %><br>
    <%= @author.favorite_authors.count %>人がこの著者をお気に入りに登録しています
  <% else %>
    この著者をお気に入りに登録しますか？
    <%= link_to "登録する", author_favorite_authors_path(@author.id), method: :post %><br>
    <%= @author.favorite_authors.count %>人がこの著者をお気に入りに登録しています
  <% end %>
</div>

<h3>著書一覧</h3>
<% @author.books.each do |book| %>
  <div>
    <%= link_to book.title, book_path(book.id) %>
  </div>
<% end %>

app/views/books/index.html.erb
<h1>本一覧</h1>

<% @books.each do |book| %>
  <div>
    <%= link_to book.title, book_path(book.id) %>
    <%= link_to book.author.name, author_path(book.author.id) %>
  </div>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.title %>'sページ</h1>

<!--本のステータス判定-->
<div>
  <% if @book_status != nil %>
    <% if @book_status.status == "check" %>
      この本のステータス：気になる本 ( 最終更新日：<%= @book_status.updated_at.strftime("%Y/%m/%d") %> )<br>
      <b><%= link_to "気になる", book_book_status_path(book_id: @book.id, id: @book_status), method: :delete %></b>
      <%= link_to "読んでいる", book_book_status_path(book_id: @book.id, id: @book_status.id, key: "read"), method: :patch %>
      <%= link_to "読み終わった", book_book_status_path(book_id: @book.id, id: @book_status.id, key: "finish"), method: :patch %>
    <% elsif @book_status.status == "read" %>
      この本のステータス：読んでいる本 ( 最終更新日：<%= @book_status.updated_at.strftime("%Y/%m/%d") %> )<br>
      <%= link_to "気になる", book_book_status_path(book_id: @book.id, id: @book_status.id, key: "check"), method: :patch %>
      <b><%= link_to "読んでいる", book_book_status_path(book_id: @book.id, id: @book_status), method: :delete %></b>
      <%= link_to "読み終わった", book_book_status_path(book_id: @book.id, id: @book_status.id, key: "finish"), method: :patch %>
    <% elsif @book_status.status == "finish" %>
      この本のステータス：読み終わった本 ( 最終更新日：<%= @book_status.updated_at.strftime("%Y/%m/%d") %> )<br>
      <%= link_to "気になる", book_book_status_path(book_id: @book.id, id: @book_status.id, key: "check"), method: :patch %>
      <%= link_to "読んでいる", book_book_status_path(book_id: @book.id, id: @book_status.id, key: "read"), method: :patch %>
      <b><%= link_to "読み終わった", book_book_status_path(book_id: @book.id, id: @book_status), method: :delete %></b>
    <% end %>
  <% else %>
    この本のステータス：ー<br>
    <%= link_to "気になる", book_book_statuses_path(@book.id, key: "check"), method: :post %>
    <%= link_to "読んでいる", book_book_statuses_path(@book.id, key: "read"), method: :post %>
    <%= link_to "読み終わった", book_book_statuses_path(@book.id, key: "finish"), method: :post %>
  <% end %>
</div>

<!--本のお気に入り判定-->
<div>
  <% if @book.favorite_book_by?(current_user) %>
    <%= link_to "本のお気に入り登録を外す", book_favorite_book_path(@book.id), method: :delete %>
  <% else %>
    <%= link_to "本をお気に入り登録する", book_favorite_book_path(@book.id), method: :post %>
  <% end %>
</div><br>

<!--本のレビュー投稿-->
※おめめマークのモーダルウィンドウにする
<% if current_user.reviews.find_by(book_id: @book) != nil %>
  <%= form_with model: [@book, @review], local: true do |f| %>
    <%= f.label :text, "レビュー" %><br>
    <%= f.text_area :text %><br>
    <%= f.submit "更新" %>
  <% end %>
  <%= link_to "レビューを削除する", book_review_path(book_id: @book.id, id: @review), method: :delete %>

<% else %>
  <%= form_with model: [@book, Review.new], local: true do |f| %>
    <%= f.label :text, "レビュー" %><br>
    <%= f.text_area :text %><br>
    <%= f.submit "投稿" %>
  <% end %>
<% end %>

<!--本のレビュー投稿表示-->
<h3>「<%= @book.title %>」に投稿されたレビュー</h3>
<% if current_user.reviews.find_by(book_id: @book) != nil %>
  <div>
    <%= link_to current_user.name+"のレビュー" %><br>
    <%= current_user.reviews.find_by(book_id: @book).text %>
    <%= current_user.reviews.find_by(book_id: @book).good_reviews.count %>いいね
  </div>
<% end %>

<% @reviews.each do |review| %>
  <div>
    <%= link_to review.user.name+"のレビュー", user_path(review.user.id) %><br>
    <%= review.text %>
    <% if review.good_review_by?(current_user) %>
      <%= link_to review.good_reviews.count.to_s+"いいね", book_review_good_reviews_path(book_id: review.book.id, review_id: review.id), method: :delete %>
    <% else %>
      <%= link_to review.good_reviews.count.to_s+"いいね", book_review_good_reviews_path(book_id: review.book.id, review_id: review.id), method: :post %>
    <% end %>
  </div>
<% end %>

<!--本のレスポンス投稿-->
<h3>「<%= @book.title %>」みんなのつぶやき</h3>
<div>
  <%= form_with model: [@book, Response.new], local: true do |f| %>
    <%= f.label :text, "お手軽投稿フォーム" %><br>
    <%= f.text_field :text %><br>
    <%= f.submit "お手軽投稿" %>
  <% end %>
</div>

<!--本のレスポンス一覧-->
<% @responses.each do |book_response| %>
<div>
  <%= link_to book_response.user.name, user_path(book_response.user.id) %>：
  <%= book_response.text %>
  <% if book_response.user_id == current_user.id %>
    <%= link_to "削除", book_response_path(book_response.book.id, book_response.id), method: :delete %>
  <% end %>
</div>
<% end %>

app/views/users/show.html.erb
<h1>マイページ</h1>

<div>
  <%= link_to "好きな作者一覧", user_favorite_authors_path(@user) %>
</div>

<div>
  <%= link_to @user.name+"さんの気になる本", user_book_statuses_path(@user, key: "check_book") %>
</div>

<div>
  <%= link_to @user.name+"さんの読んでいる本", user_book_statuses_path(@user, key: "read_book") %>
</div>

<div>
  <%= link_to @user.name+"さんの読み終わった本", user_book_statuses_path(@user, key: "finish_book") %>
</div>

<div>
  <%= link_to @user.name+"さんのお気に入りの本", user_book_statuses_path(@user, key: "favorite_book") %>
</div>

app/views/users/top.html.erb
<h1>トップページです</h1>