config/routes.rb
Rails.application.routes.draw do
  get 'book_statuses/index'
  root 'users#top'
  devise_for :users
  resources :users, only:[:show] do
    resources :favorite_authors, only:[:index]
    resources :book_statuses, only:[:index]
  end

  resources :books, only:[:show, :index] do
    resources :book_statuses, only:[:create, :update, :destroy]
    resources :reviews, only:[:create, :update, :destroy] do
      resource :good_reviews, only:[:create, :destroy]
    end
    resources :responses, only:[:create, :destroy]
    resource :favorite_book, only:[:create, :destroy]
  end

  resources :authors, only:[:show, :index] do
    resource :favorite_authors, only:[:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy

  has_many :favorite_authors, dependent: :destroy
  def favorite_author_by?(user)
    favorite_authors.where(user_id: user.id).exists?
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :book_statuses, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :responses, dependent: :destroy

  has_many :favorite_books, dependent: :destroy
  def favorite_book_by?(user)
    favorite_books.where(user_id: user.id).exists?
  end

end

app/models/book_status.rb
class BookStatus < ApplicationRecord
  belongs_to :user
  belongs_to :book

  enum status: { check: 0, read: 1, finish: 2 }

end

app/models/favorite_author.rb
class FavoriteAuthor < ApplicationRecord
  belongs_to :author
  belongs_to :user
end

app/models/favorite_book.rb
class FavoriteBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/good_review.rb
class GoodReview < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book

  has_many :good_reviews, dependent: :destroy
  def good_review_by?(user)
    good_reviews.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorite_authors, dependent: :destroy
  has_many :book_statuses, dependent: :destroy
  has_many :favorite_books, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_many :good_reviews, dependent: :destroy

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @book_status = current_user.book_statuses.find_by(book_id: @book.id)
    @review = current_user.reviews.find_by(book_id: @book)
    # 「自分以外全員」のレビューの取得
    @reviews = @book.reviews.where.not(user_id: current_user.id)
    @responses = @book.responses
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def top
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_statuses_helper.rb
module BookStatusesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/good_reviews_helper.rb
module GoodReviewsHelper
end

app/helpers/resposes_helper.rb
module ResposesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BS3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <% if user_signed_in? %>
      <nav>
        <%= link_to "トップ", root_path %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </nav>
      <nav>
        <%= current_user.name %>でログイン中
        <%= link_to "マイページ", user_path(current_user) %>
        <%= link_to "本一覧", books_path %>
        <%= link_to "著者一覧", authors_path %>
      </nav>
    <% else %>
      <nav>
        <%= link_to "トップ", root_path %>
        <%= link_to "サインイン", new_user_registration_path %>
        <%= link_to "ログイン", new_user_session_path %>
      </nav>
      <nav></nav>
    <% end %>
  </header>

  <body>
    <%= yield %>
  </body>
</html>